version: '3.8'

services:
  web:
    build: ./web
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: ./db
    ports:
      - "5000:5000"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    volumes:
      - ./document_generator:/app/document_generator
    depends_on:
      - document_generator

  document_generator:
    build: ./scripts
    command: tail -f /dev/null
